spring:
  application:
    name: apigateway-service

# Define the port where the API gateway server would be running
server:
  port: 8080

zuul:
  routes:
    uaa-service:
      sensitiveHeaders:
      path: /uaa/**
      stripPrefix: false
    writeonly-service:
      sensitiveHeaders:
      path: /writeonly/**
      url: http://localhost:8081
    public-service:
      sensitiveHeaders:
      path: /public/**
      url: http://localhost:8081
    readonly-service:
      sensitiveHeaders:
      path: /readonly/**
      url: http://localhost:8081
  add-proxy-headers: true
  
security:
  # Disable Spring Boot basic authentication
  basic:
    enabled: false
  oauth2:
    client:
      accessTokenUri: http://localhost:9999/uaa/oauth/token
      userAuthorizationUri: /uaa/oauth/authorize
      clientId: b2b
      clientSecret: b2bsecret
    resource:
      jwt:
        keyValue: |
          -----BEGIN PUBLIC KEY-----
          MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAnGp/Q5lh0P8nPL21oMMrt2RrkT9AW5jgYwLfSUnJVc9G6uR3cXRRDCjHqWU5WYwivcF180A6CWp/ireQFFBNowgc5XaA0kPpzEtgsA5YsNX7iSnUibB004iBTfU9hZ2Rbsc8cWqynT0RyN4TP1RYVSeVKvMQk4GT1r7JCEC+TNu1ELmbNwMQyzKjsfBXyIOCFU/E94ktvsTZUHF4Oq44DBylCDsS1k7/sfZC2G5EU7Oz0mhG8+Uz6MSEQHtoIi6mc8u64Rwi3Z3tscuWG2ShtsUFuNSAFNkY7LkLn+/hxLCu2bNISMaESa8dG22CIMuIeRLVcAmEWEWH5EEforTg+QIDAQAB
          -----END PUBLIC KEY-----


ratelimit:
    enabled: true #default false
    behind-proxy: true #default false
    policies:
      protected-service:
        limit: 5
        refresh-interval: 120 #60 default value (in seconds)
        type: #optional
          - user
          - origin
          - url